name: Simple enviromnet example
on: [push, workflow_dispatch, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo $SUPER_SECRET | base64
        env:
          SUPER_SECRET: ${{ secrets.AAA }}
